### ISSUE TITLE
should make chords sharable via url

### ISSUE THREAD

**Issue by rclai** [4lejandrito/react-guitar#2]
this is cool

**Comment by 4lejandrito** [comment]
Hi @rclai, thanks for suggesting this! It is a very interesting feature. 

I will play around with some ideas and come back here when I find the time.

**Comment by 4lejandrito** [comment]
Hi @rclai,

I've been playing with this. Do you think this would be a good idea?

<img width="1440" alt="Screenshot 2020-07-24 at 09 02 44" src="https://user-images.githubusercontent.com/1937354/88367619-83e28f00-cd8c-11ea-9ba3-a0d3f19da8a8.png">

Thanks!

**Comment by mrclay** [comment]
I built [this](http://mrclay.org/chord/43,59,65,69,75) for sharing chords (and short tunes). I was just thinking about making a new tab with this.

**Comment by mrclay** [comment]
@4lejandrito I like that UI. I might suggest that using a hash instead of querystring could save some bandwidth.

**Comment by 4lejandrito** [comment]
Hi @mrclay,

Thanks for the feedback, I think using a hash is indeed a better idea. I hope I can work on that soon.

Your site is really cool, it is the perfect example of a valid use case for react-guitar. If you go for it please don't hesitate to pen issues, I'll be more than happy to help.

By the way I noticed you don't name the chords on your site. It would be cool to get the chord name when the keys are pressed. I think you might be able to do that with https://github.com/tonaljs/tonal/tree/master/packages/chord-detect. I am planning to add that feature to my site too as well as adding a chord picker.

Thanks for getting in touch!

**Comment by 4lejandrito** [comment]
The copied link will include all the changed settings. For example:

https://react-guitar.com/?strings=2%7C3%7C2%7C0&tuning=69%7C64%7C60%7C67&theme=dark

Refers to a G chord on a dark ukelele.

**Comment by 4lejandrito** [comment]
I've finally kept it as a query string instead of a hash just in case I decide to do server side rendering in the future, which is possible. With a hash there is no way the server can render the page with those settings since they are not sent.

**Comment by rclai** [comment]
Sorry for not replying, but looks great man!
