### ISSUE TITLE
Play on hover

### ISSUE THREAD

**Issue by mathiasrw** [4lejandrito/react-guitar#3]
Please make the play-on-hover so it plays as if you had clicked the place you are hovering (so you can use it fo "find" cords by the sound of it.

**Comment by 4lejandrito** [comment]
Thanks @mathiasrw! 

I am not sure how to do this. If I do what you suggest it will be really hard to strum a given chord with the mouse as you would have to move it to the right fret on each string. 

I will think about it and see if I can come up with some other way.
