### ISSUE TITLE
add different tunings

### ISSUE THREAD

**Issue by markvdb** [4lejandrito/react-guitar#4]
Might want to add more tunings. The most common historical lute tuning for example (low to high), easily playable on a current day guitar:
- e, a, d, f sharp, b, e

P.S. I teach the classical guitar in public schools. Thank you! Thank you! Thank you for your effort!

**Comment by 4lejandrito** [comment]
Hi @markvdb,

I am planning to add a more comprehensive list of tunings but, for now, I added the lute one you recommended. 

You have probably the best job ever :) I started learning Spanish flamenco guitar around 3 years ago, I am still clueless but I love it.

Thanks a lot!

**Comment by markvdb** [comment]
Thank you!

**Comment by 4lejandrito** [comment]
Hi @markvdb,

I've added a new tuning selector. I'd love to hear your feedback if you read this. Check it out at https://react-guitar.com.

**Comment by janvsc** [comment]
Love it
